.MODEL SMALL
.STACK 100H 

.CODE

MAIN PROC 
   
    MOV BX,1234H;=0001 0010 0011 100 = 5(1 BITS)
    MOV AX,0    ;AX COUNTS BITS
    MOV CX,16   ;LOOP COUNTER
    
TOP:
    ROL BX,1    ;CF = BILL ROTATED OUT
    JNC NEXT    ;0 BIT
    INC AX      ;INCREMENT FOR 1 BIT
    
NEXT:
    LOOP TOP
    
;DISPLAY
    ADD AX,30H  ;FOR SHOWING IN DECIMAL
    MOV AH,2
    MOV DX,AX
    INT 21H     ;NUMBER OF 1 BITS IN BX

EXIT:    
    MOV AH,4CH
    INT 21H 
    
MAIN ENDP
END MAIN