.MODEL SMALL
.STACK 100H

MAIN PROC 
    
    ;MOV AH,1
    ;INT 21H 
    MOV AL,10110000B;A0H
    MOV BL,AL
    
;GO  TO A NEW LINE
    MOV AH,2    ;DISPLAY CHAR FUNCTION
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
                      
    
    AND BL,7FH  ;CLEARING SIGN BIT
    MOV AL,BL
    

;DISPLAY
    MOV AH,2
    MOV DL,BL
    INT 21H     ;00110000B=30H
    
    MOV AH,4CH
    INT 21H 
    
MAIN ENDP
END MAIN