.MODEL SMALL
.STACK 100H

MAIN PROC 
    
    ;MOV AH,1
    ;INT 21H 
    MOV AL,00000000B;00H=BLANK
    MOV BL,AL
    
;GO  TO A NEW LINE
    MOV AH,2    ;DISPLAY CHAR FUNCTION
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
                      
    
    OR BL,81H  ;SETTING THE MSB AND LSB
    MOV AL,BL
    

;DISPLAY
    MOV AH,2
    MOV DL,BL
    INT 21H     ;10000001=81H
    
    MOV AH,4CH
    INT 21H 
    
MAIN ENDP
END MAIN