;Write a program to read one of HEX digits A-F and display it on the next line in decimal.

.MODEL SMALL
.STACK 100H  

.DATA 

NUM DB ?
NUM1 DB '1' 
MSG1 DB "ENTER A HEX DIGIT : $" 
MSG2 DB "IN DECIMAL IT IS : $"

.CODE

MAIN PROC
       
;INITIALIZE DS 
    MOV AX,@DATA
    MOV DS,AX 
    
;DISPLAY MESSAGE
    LEA DX,MSG1 ;GET MESSAGE
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21H     ;DISPLAY MESSAGE
      
;READ INPUT
    MOV AH,1    ;READ CHAR FUNCTION
    INT 21H     ;CHAR IN AL
    MOV NUM,AL  ;SAVE IT IN CHAR1
    
    SUB NUM,11H ;AS 'A' IS 11H GREATER THAN '0' 
    
;GO  TO A NEW LINE
    MOV AH,2
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED 
    
;DISPLAY MESSAGE
    LEA DX,MSG2  ;GET MESSAGE
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21H     ;DISPLAY MESSAGE
    
;DISPLAY CHARACTER 
    MOV AH,2
    MOV DL,NUM1 ;PRINTING 1 AT FIRST
    INT 21H     ;AND DISPLAY IT 
    MOV DL,NUM  ;NOW DIGIT (0-5) NEEDED ACCORDING TO INPUT
    INT 21H     ;AND DISPLAY IT 
    
;RETURN TO DOS
    MOV AH,4CH  ;DOS EXIT FUNCTION
    INT 21H     ;EXIT TO DOS
    
MAIN ENDP
END MAIN
       
    