;Exercise 4.9: Write a program to (a) prompt the user, (b) read first, medium and last initials of a person's name and (c) display them down the left margin

.MODEL SMALL
.STACK 100H  

.DATA 

CHAR1 DB ?
CHAR2 DB ?
CHAR3 DB ?  

MSG DB "ENTER THREE INITIALS : $"

.CODE

MAIN PROC
        
;INITIALIZE DS 
    MOV AX,@DATA
    MOV DS,AX 
    
;DISPLAY MESSAGE
    LEA DX,MSG  ;GET MESSAGE
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21H     ;DISPLAY MESSAGE
         
;READ INPUT
    MOV AH,1    ;READ CHAR FUNCTION
    INT 21H     ;CHAR IN AL
    MOV CHAR1,AL;SAVE IT IN CHAR1
    INT 21H  
    MOV CHAR2,AL
    INT 21H  
    MOV CHAR3,AL  
    
;GO  TO A NEW LINE
    MOV AH,2    ;DISPLAY CHAR FUNCTION
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
    
;DISPLAY CHARACTER
    MOV DL,CHAR1;RETRIEVE CHARACTER
    INT 21H     ;AND DISPLAY IT  
    
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
    
    MOV DL,CHAR2;RETRIEVE CHARACTER     
    INT 21H     ;AND DISPLAY IT 
    
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
    
    MOV DL,CHAR3;RETRIEVE CHARACTER
    INT 21H     ;AND DISPLAY IT 
    
    MOV DL,0DH  ;CARRIAGE RETURN
    INT 21H     ;EXECUTE CARRIAGE RETURN
    MOV DL,0AH  ;LINE FEED
    INT 21H     ;EXECUTE LINE FEED
    
;RETURN TO DOS
    MOV AH,4CH  ;DOS EXIT FUNCTION
    INT 21H     ;EXIT TO DOS
    
MAIN ENDP
END MAIN
       
    